
# Q1. Where are we instantiating instances of the Property class?
  
# Q2. Where are we defining the SQL that enables us to save the ruby Property object into the database?

# Q3. In console.rb, which lines modify the database?

# Q4. Why do we not define the id of a Property object at the point we instantiate it (‘new it up’)?

# Q5. Where and how do we assign the id (that is generated by the database) to the ruby Property object?

# Q6. Why do we put a guard (an if clause) on the @id attribute in the constructor?

# Q7. Why are some of the CRUD actions represented by instance methods, and others by class methods?

# Q8. What type of data structure is returned by calls to db.exec_prepared()? In the save method, how do we access the id from the returned data structure?

# Q9. Why do we use prepared statements when performing database operations?

# Q10. What do they take in as their arguments?

# Q11. What are their return values?
